### ISSUE TITLE
Selection of Host graph in Strutural Pattern detection wizard does not work

### ISSUE THREAD

**Issue by mingqing007** [ReEng/reclipse-emf#3]
What steps will reproduce the problem?
1. Open the Structural Pattern detection wizard
2. select the host graph by clicking the select button

What is the expected output? What do you see instead?
Tree viewer of the workspace file system where sourcodedecorator file can be selected. Instead, we see empty tree viewer although there is a sourcodedecorator file in the workspace.

**Comment by mingqing007** [comment]
This is now fixed in commit r796. 
- Now the input file for the Host graph is sourcodedecorator model. However, if the user wants to use other input models, then he/she needs to type the file path manually. So, we need a better solution here, which will support multiple types of input models.

**Comment by mingqing007** [comment]
Issue 2 has been merged into this issue.

**Comment by jinyingyu** [comment]
it is fixed

**Comment by jinyingyu** [comment]
fixed already
